Tiny improvements for vscode lsp extension
aardappel/lobster pull request #318
Opened 2024-07-29 10:44 UTC by inferrna

Tiny improvements for vscode lsp extension along with new compiler argument required for that improvements.
1. Completion for builtin functions.
![image](https://github.com/user-attachments/assets/4ad2f4b9-76dc-4fd3-815c-0957089841f4)

2. Highlight signature of hovered builtin function even in error state
![image](https://github.com/user-attachments/assets/477fbc11-ba5b-410f-9560-32d8a28dee4e)

2024-07-29 15:55 UTC, aardappel commented
Thanks!
@ewoudje can you review this?

2024-07-29 23:40 UTC, ewoudje requested changes
Very nice additions. 
Everything looks good to me except the location of the code of initialization and usage of the docs.

And thanks for fixing the typos, totally overlooked those😅

2024-07-29 23:40 UTC, ewoudje commented on dev/lsp/src/features/completion.ts
> +export function getFunctionSignature(
This shouldn't be in a feature since its not only for this feature. Features are meant to be fully independent of eachother.

2024-07-29 23:40 UTC, ewoudje commented on dev/lsp/src/features/completion.ts
> +        builtinsDoc = await getBuiltinsDoc(settings);
Same as above shouldn't be in this feature, should prob be stored in LSPInstance

2024-07-30 14:45 UTC, inferrna commented on dev/src/compiler.cpp
> +        for (auto [i, a] : enumerate(nf->args)) {
It's not so easy to do, especially because I don't group items by subsystem in JSON output.

2024-07-30 15:55 UTC, aardappel commented on dev/src/compiler.cpp
> +        for (auto [i, a] : enumerate(nf->args)) {
I'm sure it can be done.. the code looks almost identical :)

2024-07-31 20:26 UTC, inferrna commented on dev/src/compiler.cpp
> +        for (auto [i, a] : enumerate(nf->args)) {
Done. Also added --gen-builtins-html-ng option to generate flat html doc.

2024-07-31 21:16 UTC, aardappel commented on dev/src/compiler.cpp
> +    string jsonTags[16][2] = {
this codebase doesn't use `camelCase` anywhere, for vars it be `snake_case`, please fix all new identifiers in this PR.

2024-08-01 18:03 UTC, aardappel commented
LGTM, thanks @inferrna !

2024-08-01 18:03 UTC, merged